preset: symfony

enabled:
    - concat_with_spaces
    - ordered_use

disabled:
    - concat_without_spaces
    - phpdoc_align
    - phpdoc_indent
    - phpdoc_to_comment
    - blankline_after_open_tag
    - function_declaration
    - single_line_class_definition
    - single_line_throw
